### ISSUE TITLE
Fail to run `azd provision`

### ISSUE THREAD

**Issue by NanaXiong00** [marnixcox/integration-hub#3]
**Describe the issue:**
When running `azd up`, the following error occurs:
![image](https://github.com/user-attachments/assets/7c0b19d9-ef76-428b-bd86-292424179692)

**Repro Steps:**
1. Run `azd auth login`
2. Run `azd init -t azd init -t https://github.com/marnixcox/integration-hub`
3. Run `azd provision`

**Environment:**
- azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
- OS: Windows

**Expected behavior:**
Run `azd provision` can successfully.

@hemarina and @marnixcox  for notification.

**Comment by marnixcox** [comment]
@NanaXiong00 Thanks for testing. I have now made the Key Vault name a little bit smaller and restricted the environment name length

**Comment by NanaXiong00** [comment]
@marnixcox Thanks for your reply, retested based on the latest code and no such issue. The issue is now closed.
